### ISSUE TITLE
user.depopulate('password') is invalid

### ISSUE THREAD

**Issue by SirM2z** [kelvin-mai/nest-commerce#3]
'password' still return when login or register, but it work in your video.

my project dependencies:

"@nestjs/mongoose": "^6.1.2"
"mongoose": "^5.5.5"

mongodb version: v4.0.2

I clone this project, but it didn't work.

**Comment by kelvin-mai** [comment]
Thanks for bringing this up, there's a bug with mongoose depopulate in version 5.4.2 I added a temporary fix in commit commit-68e1598bea1793b4aaca2d1ca9a6dd6f23749800

**Comment by SirM2z** [comment]
Thanks for your reply.
